# Generated by Django 5.0.2 on 2024-04-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaManutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tutulo",
                    models.CharField(
                        choices=[
                            ("TVM", "Trocar valvula do motor"),
                            ("TO", "Troca de oleo"),
                            ("BL", "Balanceamento"),
                        ],
                        max_length=3,
                    ),
                ),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name="servico",
            name="data_entrega",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="data_inicio",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="finalizado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servico",
            name="protocolo",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="categoria_manutencao",
            field=models.ManyToManyField(to="servicos.categoriamanutencao"),
        ),
    ]
