# Generated by Django 5.0.2 on 2024-04-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0002_categoriamanutencao_servico_data_entrega_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoriamanutencao",
            old_name="tutulo",
            new_name="titulo",
        ),
    ]
