# Generated by Django 5.0.2 on 2024-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0003_rename_tutulo_categoriamanutencao_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="protocolo",
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
