# Generated by Django 5.0.2 on 2024-07-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0004_alter_servico_protocolo"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="identificador",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
